services:
  app-core:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    logging:
      driver: loki
      options:
        loki-url: "http://monitor.study-up.site:3100/loki/api/v1/push"
