services:
  app-core:
    container_name: web-application-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    network_mode: "host"
    logging:
      driver: loki
      options:
        loki-url: "http://monitor.study-up.site:3100/loki/api/v1/push"
