spring:
  application:
    name: study-up-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study_up?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # TODO: change to validate

authentication:
  refresh-token:
    expiration-in-minutes: ${REFRESH_TOKEN_EXPIRATION_IN_MINUTES}
  access-token:
    secret: ${ACCESS_TOKEN_SECRET}
    expiration-in-milliseconds: ${ACCESS_TOKEN_EXPIRATION_IN_MILLISECONDS}

springdoc:
  swagger-ui:
    path: /docs/index.html
    disable-swagger-default-url: true
  api-docs:
    path: /docs
