name: Continuous Integration
on: pull_request

jobs:
  analyze:
    runs-on: ubuntu-24.04

    steps:
      - name: Set up sources
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
          cache: gradle

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Grant permission to `gradlew`
        run: chmod +x gradlew

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build jacocoTestReport sonar --info

      - name: Upload Gradle report
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: gradle-report
          path: build/reports
